import {int, boolean, json, mysqlTableCreator, varchar} from "drizzle-orm/mysql-core";

export const planetScaleTable = mysqlTableCreator((name) => `dota_ps_${name}`);
export const hero_stats = planetScaleTable('hero_stats', {
    id: int('id').primaryKey().notNull(),
    name: varchar('name', {length: 256}),
    localized_name: varchar('name', {length: 256}),
    primary_attr: varchar('primary_attr', { length: 256}),
    attack_type: varchar('attack_type', { length: 256}),
    roles: json('roles').$type<string[]>(),
    icon: varchar('icon', { length: 256}),
    base_health: int('base_health'),
    base_health_regen: int('base_health_regen'),
    base_mana: int('base_mana'),
    base_mana_regen: int('base_mana_regen'),
    base_armor: int('base_armor'),
    base_mr: int('base_mr'),
    base_attack_min: int('base_attack_min'),
    base_attack_max: int('base_attack_max'),
    base_str: int('base_str'),
    base_agi: int('base_agi'),
    base_int: int('base_int'),
    str_gain: int('str_gain'),
    agi_gain: int('agi_gain'),
    int_gain: int('int_gain'),
    attack_range: int('attack_range'),
    projectile_speed: int('projectile_speed'),
    attack_rate: int('attack_rate'),
    base_attack_time: int('base_attack_time'),
    attack_point: int('attack_point'),
    move_speed: int('move_speed'),
    turn_rate: int('turn_rate'),
    cm_enabled: boolean('cm_enabled'),
    legs: int('legs'),
    day_vision: int('day_vision'),
    night_vision: int('night_vision'),
    hero_id: int('hero_id'),
    turbo_picks: int('turbo_pics'),
    turbo_wins: int('turbo_wins'),
    pro_ban: int('pro_ban'),
    pro_win: int('pro_win'),
    pro_pick: int('pro_pick'),
    one_pick: int('1_pick'),
    one_win: int('1_win'),
    two_pick: int('2_pick'),
    two_win: int('2_win'),
    three_pick: int('3_pick'),
    three_win: int('3_win'),
    four_pick: int('4_pick'),
    four_win: int('4_win'),
    five_pick: int('5_pick'),
    five_win: int('5_win'),
    six_pick: int('6_pick'),
    six_win: int('6_win'),
    seven_pick: int('7_pick'),
    seven_win: int('7_win'),
    eight_pick: int('8_pick'),
    eight_win: int('8_win'),
    null_pick: int('null_pick'),
    null_win: int('null_win')
});