import {int, boolean, json, mysqlTableCreator, varchar, bigint, primaryKey} from "drizzle-orm/mysql-core";

export const planetScaleTable = mysqlTableCreator((name) => `dota_ps_${name}`);
export const hero_stats = planetScaleTable('hero_stats', {
    id: int('id').primaryKey().notNull(),
    name: varchar('name', {length: 256}).notNull(),
    localized_name: varchar('localized_name', {length: 256}).notNull(),
    primary_attr: varchar('primary_attr', { length: 256}).notNull(),
    attack_type: varchar('attack_type', { length: 256}),
    roles: json('roles').$type<string[]>(),
    img: varchar('img', { length: 256}),
    icon: varchar('icon', { length: 256}),
    base_health: int('base_health'),
    base_health_regen: int('base_health_regen'),
    base_mana: int('base_mana'),
    base_mana_regen: int('base_mana_regen'),
    base_armor: int('base_armor'),
    base_mr: int('base_mr'),
    base_attack_min: int('base_attack_min'),
    base_attack_max: int('base_attack_max'),
    base_str: int('base_str'),
    base_agi: int('base_agi'),
    base_int: int('base_int'),
    str_gain: int('str_gain'),
    agi_gain: int('agi_gain'),
    int_gain: int('int_gain'),
    attack_range: int('attack_range'),
    projectile_speed: int('projectile_speed'),
    attack_rate: int('attack_rate'),
    base_attack_time: int('base_attack_time'),
    attack_point: int('attack_point'),
    move_speed: int('move_speed'),
    turn_rate: int('turn_rate'),
    cm_enabled: boolean('cm_enabled'),
    legs: int('legs'),
    day_vision: int('day_vision'),
    night_vision: int('night_vision'),
    hero_id: int('hero_id'),
    turbo_picks: int('turbo_pics'),
    turbo_wins: int('turbo_wins'),
    pro_ban: int('pro_ban'),
    pro_win: int('pro_win'),
    pro_pick: int('pro_pick'),
    one_pick: int('one_pick'),
    one_win: int('one_win'),
    two_pick: int('two_pick'),
    two_win: int('two_win'),
    three_pick: int('three_pick'),
    three_win: int('three_win'),
    four_pick: int('four_pick'),
    four_win: int('four_win'),
    five_pick: int('five_pick'),
    five_win: int('five_win'),
    six_pick: int('six_pick'),
    six_win: int('six_win'),
    seven_pick: int('seven_pick'),
    seven_win: int('seven_win'),
    eight_pick: int('eight_pick'),
    eight_win: int('eight_win'),
    null_pick: int('null_pick'),
    null_win: int('null_win')
});

export const hero_item_usages = planetScaleTable('hero_item_usages', {
    hero_id: int('hero_id').notNull(),
    item_id: int('item_id').notNull(),
    item_name: varchar('item_name', {length: 256}).notNull(),
    win_rate: bigint('win_rate', {mode: 'number'}).notNull(),
    matches: bigint('matches', {mode: 'number'}).notNull()
}, (table) => {
    return {
        pk: primaryKey({ columns: [table.hero_id, table.item_id] }),
        pkWithCustomName: primaryKey({ name: 'hero_item_id', columns: [table.hero_id, table.item_id] }),
    }});