import {scalarOptions} from "yaml";
import Null = scalarOptions.Null;

export interface HeroStat{
    id: number;
    name: string;
    localized_name: string;
    primary_attr: string;
    attack_type: string | null;
    roles: string[] | null;
    img: string | null;
    icon: string | null;
    base_health: number | null;
    base_health_regen: number | null;
    base_mana: number | null;
    base_mana_regen: number | null;
    base_armor: number | null;
    base_mr: number | null;
    base_attack_min: number | null;
    base_attack_max: number | null;
    base_str: number | null;
    base_agi: number | null;
    base_int: number | null;
    str_gain: number | null;
    agi_gain: number | null;
    int_gain: number | null;
    attack_range: number | null;
    projectile_speed: number | null;
    attack_rate: number | null;
    base_attack_time: number | null;
    attack_point: number | null;
    move_speed: number | null;
    turn_rate: number | null;
    cm_enabled: boolean | null;
    legs: number | null;
    day_vision: number | null;
    night_vision: number | null;
    hero_id: number | null;
    turbo_picks: number | null;
    turbo_wins: number | null;
    pro_ban: number | null;
    pro_win: number | null;
    pro_pick: number | null;
    one_pick: number | null;
    one_win: number | null;
    two_pick: number | null;
    two_win: number | null;
    three_pick: number | null;
    three_win: number | null;
    four_pick: number | null;
    four_win: number | null;
    five_pick: number | null;
    five_win: number | null;
    six_pick: number | null;
    six_win: number | null;
    seven_pick: number | null;
    seven_win: number | null;
    eight_pick: number | null;
    eight_win: number | null;
    null_pick: number | null;
    null_win: number | null;
}

